name = "ITC LAND SYSTEMS GM"
prefix = "itc_land_systems_gm"
author = "Nomisum, Salbei"
files = [
    "mod.cpp",
    "itc-combo.paa",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip itc_land_systems_gm_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"